class Cat
  def initialize(name)
    @name = name
  end

  def untested
    puts "no tests for this method yet"
    puts "no te sts for this method yet"
    puts "no tes ts for this method yet"
    puts "no tests for this method yet"
        puts "no tests for this method yet"

    puts "no tests for this method yet"
  end

  def untested_two
     puts "no tests for this method either"
    puts "no tests for this method either"
    puts "no tests for this method either"
    puts "no tests for this method either"
    puts "no tests for this method either"
    puts "no tests for this method either"
         puts "no tests for this method either"
    puts "no tests for this method either"
    puts "no tests for this method either"
    puts "no tests for this method either"
    puts "no tests for this method either"
         puts "no tests for this method either"
    puts "no tests for this method either"
    puts "no tests for this method either"
    puts "no tests for this method either"
    puts "no tests for this method either"
         puts "no tests for this method either"
    puts "no tests for this method either"
    puts "no tests for this method either"
    puts "no tests for this method either"
    puts "no tests for this method either"
         puts "no tests for this method either"
    puts "no tests for this method either"
    puts "no tests for this method either"
    puts "no tests for this method either"
    puts "no tests for this method either"
         puts "no tests for this method either"
    puts "no tests for this method either"
    puts "no tests for this method either"
    puts "no tests for this method either"
    puts "no tests for this method either"
         puts "no tests for this method either"
    puts "no tests for this method either"
    puts "no tests for this method either"
    puts "no tests for this method either"
    puts "no tests for this method either"
         puts "no tests for this method either"
    puts "no tests for this method either"
    puts "no tests for this method either"
    puts "no tests for this method either"
    puts "no tests for this method either"
         puts "no tests for this method either"
    puts "no tests for this method either"
    puts "no tests for this method either"
    puts "no tests for this method either"
    puts "no tests for this method either"
         puts "no tests for this method either"
    puts "no tests for this method either"
    puts "no tests for this method either"
    puts "no tests for this method either"
    puts "no tests for this method either"
         puts "no tests for this method either"
    puts "no tests for this method either"
    puts "no tests for this method either"
    puts "no tests for this method either"
    puts "no tests for this method either"
         puts "no tests for this method either"
    puts "no tests for this method either"
    puts "no tests for this method either"
    puts "no tests for this method either"
    puts "no tests for this method either"
         puts "no tests for this method either"
    puts "no tests for this method either"
    puts "no tests for this method either"
    puts "no tests for this method either"
    puts "no tests for this method either"
         puts "no tests for this method either"
    puts "no tests for this method either"
    puts "no tests for this method either"
    puts "no tests for this method either"
    puts "no tests for this method either"
         puts "no tests for this method either"
    puts "no tests for this method either"
    puts "no tests for this method either"
    puts "no tests for this method either"
    puts "no tests for this method either"
         puts "no tests for this method either"
    puts "no tests for this method either"
    puts "no tests for this method either"
    puts "no tests for this method either"
    puts "no tests for this method either"
         puts "no tests for this method either"
    puts "no tests for this method either"
    puts "no tests for this method either"
    puts "no tests for this method either"
    puts "no tests for this method either"
  end

  def untested_three
    puts "no tests for this method either"
     puts "no tests for this method either"
    puts "no  tests for this method either"
     puts "no  tests for this method either"
    puts "no tests for this method either"
    puts "no tests for this me thod either"
  end

  def problematic
    # FIXME
  end
end
